### ISSUE TITLE
Display number of passive listeners in basement

### ISSUE THREAD

**Issue by chrisrohn** [mxew/firetable-user#143] opened 2021-02-26 22:37 UTC
in the Everyone (x+y+z) count, also display number of Shoutcast(y) and Icecast(z) listeners. If there is a way to also display passive listeners that aren't signed in the basement, that would be amazing, too. It would help extend the fact that we are not just dj'ing with ourselves.

Everyone (x+y+z)

Firetable (x)
username
username
username
TuneIn (y)
Web Page (z)

**Comment by mxew** [comment] 2021-03-01 03:38
duplicate of #15

**Closed as completed by mxew** 2021-03-01 03:38 UTC
Labels: duplicate
